#!/usr/bin/env python3
import paho.mqtt.client as mqtt
import json
import time

BROKER_IP = "127.0.0.1"
BROKER_PORT = 1883

MQTT_TOPIC_COMMAND = "edgeimpulse/command"
MQTT_TOPIC_ALERT = "edgeimpulse/alert"

RPI_ID = "RPI_TRANSMITTER"


def on_connect(client, userdata, flags, rc):
    print(f"[transmitter] Connected ({rc})")
    client.subscribe(MQTT_TOPIC_ALERT)


def on_message(client, userdata, msg):
    try:
        payload = json.loads(msg.payload.decode())
        print("\n===== EDGE IMPULSE DETECTION =====")
        print(json.dumps(payload, indent=4))
        print("==================================\n")
    except:
        print("[transmitter] Invalid alert.")


client = mqtt.Client()
client.on_connect = on_connect
client.on_message = on_message

client.connect(BROKER_IP, BROKER_PORT, 60)
client.loop_start()

command_payload = {
    "rpi_id": RPI_ID,
    "command": "start_edge_impulse"
}

client.publish(MQTT_TOPIC_COMMAND, json.dumps(command_payload))
print("[transmitter] Sent START command")

try:
    while True:
        time.sleep(1)
except KeyboardInterrupt:
    pass
