#!/usr/bin/env python3
import paho.mqtt.client as mqtt, json, time

BROKER_IP = "127.0.0.1" #
BROKER_PORT = 1883
MQTT_TOPIC_COMMAND = "edgeimpulse/command"
MQTT_TOPIC_ALERT = "edgeimpulse/alert"
RPI_ID = "RPI_TRANSMITTER"

def on_connect(client, userdata, flags, rc):
    print(f"[transmitter] ✅ Conectado MQTT ({rc})")
    client.subscribe(MQTT_TOPIC_ALERT)

def on_message(client, userdata, msg):
    try:
        payload = json.loads(msg.payload.decode())
        print(f"[transmitter] 🚨 FIRE DETECTADO en receptor: {payload}")
    except Exception:
        print(f"[transmitter] ⚠️ Mensaje inválido: {msg.payload}")

client = mqtt.Client()
client.on_connect = on_connect
client.on_message = on_message
client.connect(BROKER_IP, BROKER_PORT, 60)
client.loop_start()

command_payload = {"rpi_id": RPI_ID, "command": "start_edge_impulse"}
client.publish(MQTT_TOPIC_COMMAND, json.dumps(command_payload))
print("[transmitter] ▶️ Señal enviada para iniciar Edge Impulse en receptor.")

try:
    while True:
        time.sleep(1)
except KeyboardInterrupt:
    print("[transmitter] 🧩 Finalizando...")
finally:
    client.loop_stop()
    client.disconnect()
